name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Change to '3.11' if you want to use Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools==67.8.0  # Keep the compatible version of setuptools
        pip install -r requirements.txt  # Install other dependencies

    - name: Run tests
      run: |
        pytest  # Or the command you use to run your tests

    - name: Clean up
      run: |
        echo "Cleaning up..."
